In [31]:
import tensorflow as tf
import numpy as np

In [3]:
# 텐서플로우에서 제공하는 MNIST데이터를 사용하겠다
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [28]:
# 데이터의 로딩 완료 여부를 확인
print('x_train.shape : ', x_train.shape)
print('y_train.shape : ', y_train.shape)
print('x_test.shape : ', x_test.shape)
print('y_test.shape : ', y_test.shape)


x_train.shape :  (60000, 28, 28)
y_train.shape :  (60000,)
x_test.shape :  (10000, 28, 28)
y_test.shape :  (10000,)


In [33]:
# 결과 값의 종류 확인
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [27]:
# 이미지 데이터의 픽섹 범위는 0~255이므로 255로 나누어 0~1사이 범위로 변경 255.0은 샘플 데이터를 정수에서 부동소수점 숫자로 바꾸어준다.
x_train, x_test = x_train / 255.0, x_test / 255.0


In [34]:
# 모델구축
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [37]:
# 학습을 진행하기 전 초기 모델의 weight, bias의 값을 통해 나온 예측값
pred = model(x_train[:1]).numpy()
pred

array([[-0.02172713,  0.0395346 ,  0.07891425,  0.28208813,  0.09572585,
         0.34163523, -0.24602148, -0.07933238, -0.4145444 ,  0.29774955]],
      dtype=float32)

In [38]:
# 해당 결과를 softmax함수를 통과 시켜서 결과를 확률로 변환한다.
tf.nn.softmax(pred).numpy()

array([[0.09189889, 0.09770481, 0.10162915, 0.12452473, 0.10335214,
        0.13216503, 0.07343455, 0.08675463, 0.06204573, 0.12649031]],
      dtype=float32)

In [40]:
# 학습에 사용할 loss_function 정의
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
# 위의 from_logits 은 현재의 모델이 sigmoid나 softmax함수를 통과한 확률값이 아니므로 True값으로 적용(확률일 경우 False)
loss_fn(y_train[:1], pred).numpy()
# 훈련되지 않은 모델의 초기 로스는 tf.math.log(1/10) ~= 2.3 에 가깝다.

2.0237038

In [41]:
# 학습을 위한 옵티마이저와 손실함수, 평가지표를 지정
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [48]:
# 모델을 2번만 학습시킨다
model.fit(x_train, y_train, epochs=2)


Epoch 1/2
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0376 - accuracy: 0.9871
Epoch 2/2
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0346 - accuracy: 0.9883


In [49]:
# 학습이 잘 진행되었는지 테스트 데이터를 넣어본다.
model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0862 - accuracy: 0.9796


[0.08623508363962173, 0.9796000123023987]